/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteImport } from './routes/_main'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as MainSettingsRouteImport } from './routes/_main/settings'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as MainMarketplaceIndexRouteImport } from './routes/_main/marketplace/index'
import { Route as MainGroupsIndexRouteImport } from './routes/_main/groups/index'
import { Route as MainFeedIndexRouteImport } from './routes/_main/feed/index'
import { Route as MainEventsIndexRouteImport } from './routes/_main/events/index'
import { Route as MainProfileUsernameRouteImport } from './routes/_main/profile/$username'
import { Route as MainMarketplaceNewRouteImport } from './routes/_main/marketplace/new'
import { Route as MainMarketplaceIdRouteImport } from './routes/_main/marketplace/$id'
import { Route as MainGroupsNewRouteImport } from './routes/_main/groups/new'
import { Route as MainGroupsSlugRouteImport } from './routes/_main/groups/$slug'
import { Route as MainFeedSearchRouteImport } from './routes/_main/feed/search'
import { Route as MainFeedNewRouteImport } from './routes/_main/feed/new'
import { Route as MainFeedIdRouteImport } from './routes/_main/feed/$id'
import { Route as MainEventsNewRouteImport } from './routes/_main/events/new'
import { Route as MainEventsIdRouteImport } from './routes/_main/events/$id'

const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const MainSettingsRoute = MainSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MainRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const MainMarketplaceIndexRoute = MainMarketplaceIndexRouteImport.update({
  id: '/marketplace/',
  path: '/marketplace/',
  getParentRoute: () => MainRoute,
} as any)
const MainGroupsIndexRoute = MainGroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => MainRoute,
} as any)
const MainFeedIndexRoute = MainFeedIndexRouteImport.update({
  id: '/feed/',
  path: '/feed/',
  getParentRoute: () => MainRoute,
} as any)
const MainEventsIndexRoute = MainEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => MainRoute,
} as any)
const MainProfileUsernameRoute = MainProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => MainRoute,
} as any)
const MainMarketplaceNewRoute = MainMarketplaceNewRouteImport.update({
  id: '/marketplace/new',
  path: '/marketplace/new',
  getParentRoute: () => MainRoute,
} as any)
const MainMarketplaceIdRoute = MainMarketplaceIdRouteImport.update({
  id: '/marketplace/$id',
  path: '/marketplace/$id',
  getParentRoute: () => MainRoute,
} as any)
const MainGroupsNewRoute = MainGroupsNewRouteImport.update({
  id: '/groups/new',
  path: '/groups/new',
  getParentRoute: () => MainRoute,
} as any)
const MainGroupsSlugRoute = MainGroupsSlugRouteImport.update({
  id: '/groups/$slug',
  path: '/groups/$slug',
  getParentRoute: () => MainRoute,
} as any)
const MainFeedSearchRoute = MainFeedSearchRouteImport.update({
  id: '/feed/search',
  path: '/feed/search',
  getParentRoute: () => MainRoute,
} as any)
const MainFeedNewRoute = MainFeedNewRouteImport.update({
  id: '/feed/new',
  path: '/feed/new',
  getParentRoute: () => MainRoute,
} as any)
const MainFeedIdRoute = MainFeedIdRouteImport.update({
  id: '/feed/$id',
  path: '/feed/$id',
  getParentRoute: () => MainRoute,
} as any)
const MainEventsNewRoute = MainEventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => MainRoute,
} as any)
const MainEventsIdRoute = MainEventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => MainRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/settings': typeof MainSettingsRoute
  '/events/$id': typeof MainEventsIdRoute
  '/events/new': typeof MainEventsNewRoute
  '/feed/$id': typeof MainFeedIdRoute
  '/feed/new': typeof MainFeedNewRoute
  '/feed/search': typeof MainFeedSearchRoute
  '/groups/$slug': typeof MainGroupsSlugRoute
  '/groups/new': typeof MainGroupsNewRoute
  '/marketplace/$id': typeof MainMarketplaceIdRoute
  '/marketplace/new': typeof MainMarketplaceNewRoute
  '/profile/$username': typeof MainProfileUsernameRoute
  '/events/': typeof MainEventsIndexRoute
  '/feed/': typeof MainFeedIndexRoute
  '/groups/': typeof MainGroupsIndexRoute
  '/marketplace/': typeof MainMarketplaceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof MainIndexRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/settings': typeof MainSettingsRoute
  '/events/$id': typeof MainEventsIdRoute
  '/events/new': typeof MainEventsNewRoute
  '/feed/$id': typeof MainFeedIdRoute
  '/feed/new': typeof MainFeedNewRoute
  '/feed/search': typeof MainFeedSearchRoute
  '/groups/$slug': typeof MainGroupsSlugRoute
  '/groups/new': typeof MainGroupsNewRoute
  '/marketplace/$id': typeof MainMarketplaceIdRoute
  '/marketplace/new': typeof MainMarketplaceNewRoute
  '/profile/$username': typeof MainProfileUsernameRoute
  '/events': typeof MainEventsIndexRoute
  '/feed': typeof MainFeedIndexRoute
  '/groups': typeof MainGroupsIndexRoute
  '/marketplace': typeof MainMarketplaceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_main': typeof MainRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_main/settings': typeof MainSettingsRoute
  '/_main/': typeof MainIndexRoute
  '/_main/events/$id': typeof MainEventsIdRoute
  '/_main/events/new': typeof MainEventsNewRoute
  '/_main/feed/$id': typeof MainFeedIdRoute
  '/_main/feed/new': typeof MainFeedNewRoute
  '/_main/feed/search': typeof MainFeedSearchRoute
  '/_main/groups/$slug': typeof MainGroupsSlugRoute
  '/_main/groups/new': typeof MainGroupsNewRoute
  '/_main/marketplace/$id': typeof MainMarketplaceIdRoute
  '/_main/marketplace/new': typeof MainMarketplaceNewRoute
  '/_main/profile/$username': typeof MainProfileUsernameRoute
  '/_main/events/': typeof MainEventsIndexRoute
  '/_main/feed/': typeof MainFeedIndexRoute
  '/_main/groups/': typeof MainGroupsIndexRoute
  '/_main/marketplace/': typeof MainMarketplaceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/settings'
    | '/events/$id'
    | '/events/new'
    | '/feed/$id'
    | '/feed/new'
    | '/feed/search'
    | '/groups/$slug'
    | '/groups/new'
    | '/marketplace/$id'
    | '/marketplace/new'
    | '/profile/$username'
    | '/events/'
    | '/feed/'
    | '/groups/'
    | '/marketplace/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/settings'
    | '/events/$id'
    | '/events/new'
    | '/feed/$id'
    | '/feed/new'
    | '/feed/search'
    | '/groups/$slug'
    | '/groups/new'
    | '/marketplace/$id'
    | '/marketplace/new'
    | '/profile/$username'
    | '/events'
    | '/feed'
    | '/groups'
    | '/marketplace'
  id:
    | '__root__'
    | '/_auth'
    | '/_main'
    | '/_auth/login'
    | '/_auth/register'
    | '/_main/settings'
    | '/_main/'
    | '/_main/events/$id'
    | '/_main/events/new'
    | '/_main/feed/$id'
    | '/_main/feed/new'
    | '/_main/feed/search'
    | '/_main/groups/$slug'
    | '/_main/groups/new'
    | '/_main/marketplace/$id'
    | '/_main/marketplace/new'
    | '/_main/profile/$username'
    | '/_main/events/'
    | '/_main/feed/'
    | '/_main/groups/'
    | '/_main/marketplace/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  MainRoute: typeof MainRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/settings': {
      id: '/_main/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof MainSettingsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_main/marketplace/': {
      id: '/_main/marketplace/'
      path: '/marketplace'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof MainMarketplaceIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/groups/': {
      id: '/_main/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof MainGroupsIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/feed/': {
      id: '/_main/feed/'
      path: '/feed'
      fullPath: '/feed/'
      preLoaderRoute: typeof MainFeedIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/events/': {
      id: '/_main/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof MainEventsIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/profile/$username': {
      id: '/_main/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof MainProfileUsernameRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/marketplace/new': {
      id: '/_main/marketplace/new'
      path: '/marketplace/new'
      fullPath: '/marketplace/new'
      preLoaderRoute: typeof MainMarketplaceNewRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/marketplace/$id': {
      id: '/_main/marketplace/$id'
      path: '/marketplace/$id'
      fullPath: '/marketplace/$id'
      preLoaderRoute: typeof MainMarketplaceIdRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/groups/new': {
      id: '/_main/groups/new'
      path: '/groups/new'
      fullPath: '/groups/new'
      preLoaderRoute: typeof MainGroupsNewRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/groups/$slug': {
      id: '/_main/groups/$slug'
      path: '/groups/$slug'
      fullPath: '/groups/$slug'
      preLoaderRoute: typeof MainGroupsSlugRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/feed/search': {
      id: '/_main/feed/search'
      path: '/feed/search'
      fullPath: '/feed/search'
      preLoaderRoute: typeof MainFeedSearchRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/feed/new': {
      id: '/_main/feed/new'
      path: '/feed/new'
      fullPath: '/feed/new'
      preLoaderRoute: typeof MainFeedNewRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/feed/$id': {
      id: '/_main/feed/$id'
      path: '/feed/$id'
      fullPath: '/feed/$id'
      preLoaderRoute: typeof MainFeedIdRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/events/new': {
      id: '/_main/events/new'
      path: '/events/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof MainEventsNewRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/events/$id': {
      id: '/_main/events/$id'
      path: '/events/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof MainEventsIdRouteImport
      parentRoute: typeof MainRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface MainRouteChildren {
  MainSettingsRoute: typeof MainSettingsRoute
  MainIndexRoute: typeof MainIndexRoute
  MainEventsIdRoute: typeof MainEventsIdRoute
  MainEventsNewRoute: typeof MainEventsNewRoute
  MainFeedIdRoute: typeof MainFeedIdRoute
  MainFeedNewRoute: typeof MainFeedNewRoute
  MainFeedSearchRoute: typeof MainFeedSearchRoute
  MainGroupsSlugRoute: typeof MainGroupsSlugRoute
  MainGroupsNewRoute: typeof MainGroupsNewRoute
  MainMarketplaceIdRoute: typeof MainMarketplaceIdRoute
  MainMarketplaceNewRoute: typeof MainMarketplaceNewRoute
  MainProfileUsernameRoute: typeof MainProfileUsernameRoute
  MainEventsIndexRoute: typeof MainEventsIndexRoute
  MainFeedIndexRoute: typeof MainFeedIndexRoute
  MainGroupsIndexRoute: typeof MainGroupsIndexRoute
  MainMarketplaceIndexRoute: typeof MainMarketplaceIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainSettingsRoute: MainSettingsRoute,
  MainIndexRoute: MainIndexRoute,
  MainEventsIdRoute: MainEventsIdRoute,
  MainEventsNewRoute: MainEventsNewRoute,
  MainFeedIdRoute: MainFeedIdRoute,
  MainFeedNewRoute: MainFeedNewRoute,
  MainFeedSearchRoute: MainFeedSearchRoute,
  MainGroupsSlugRoute: MainGroupsSlugRoute,
  MainGroupsNewRoute: MainGroupsNewRoute,
  MainMarketplaceIdRoute: MainMarketplaceIdRoute,
  MainMarketplaceNewRoute: MainMarketplaceNewRoute,
  MainProfileUsernameRoute: MainProfileUsernameRoute,
  MainEventsIndexRoute: MainEventsIndexRoute,
  MainFeedIndexRoute: MainFeedIndexRoute,
  MainGroupsIndexRoute: MainGroupsIndexRoute,
  MainMarketplaceIndexRoute: MainMarketplaceIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  MainRoute: MainRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
